print("Monkey Draw Starting...")
import turtle
def draw_monkey():
    # Head
    turtle.color("brown")
    turtle.begin_fill()
    turtle.circle(50)
    turtle.end_fill()
    # Eyes
    turtle.color("white")
    turtle.begin_fill()
    turtle.circle(10)
    turtle.end_fill()
    turtle.color("black")
    turtle.begin_fill()
    turtle.circle(5)
    turtle.end_fill()
    turtle.penup()
    turtle.goto(25, 50)
    turtle.pendown()
    turtle.color("white")
    turtle.begin_fill()
    turtle.circle(10)
    turtle.end_fill()
    turtle.color("black")
    turtle.begin_fill()
    turtle.circle(5)
    turtle.end_fill()
    
    # Nose
    turtle.color("black")
    turtle.penup()
    turtle.goto(0, 25)
    turtle.pendown()
    turtle.begin_fill()
    turtle.circle(7)
    turtle.end_fill()
    # Mouth
    turtle.color("black")
    turtle.penup()
    turtle.goto(-10, 10)
    turtle.pendown()
    turtle.pensize(3)
    turtle.right(90)
    turtle.forward(20)
    turtle.left(90)
    turtle.forward(20)
    turtle.left(90)
    turtle.forward(20)
    turtle.left(90)
    turtle.forward(20)
    turtle.pensize(1)
    # Ears
    turtle.color("brown")
    turtle.penup()
    turtle.goto(-50, 50)
    turtle.pendown()
    turtle.begin_fill()
    turtle.circle(15)
    turtle.end_fill()
    turtle.penup()
    turtle.goto(50, 50)
    turtle.pendown()
    turtle.begin_fill()
    turtle.circle(15)
    turtle.end_fill()
    
    # Arms
    turtle.color("brown")
    turtle.penup()
    turtle.goto(-60, 0)
    turtle.pendown()
    turtle.right(90)
    turtle.forward(60)
    turtle.left(90)
    turtle.forward(20)
    turtle.left(90)
    turtle.forward(60)
    turtle.penup()
    turtle.goto(60, 0)
    turtle.pendown()
    turtle.left(90)
    turtle.forward(60)
    turtle.right(90)
    turtle.forward(20)
    turtle.right(90)
    turtle.forward(60)
    # Legs
    turtle.color("brown")
    turtle.penup()
    turtle.goto(-35, -50)
    turtle.pendown()
    turtle.right(90)
    turtle.forward(50)
    turtle.left(90)
    turtle.forward(20)
    turtle.left(90)
    turtle.forward(50)